snowflake:
  account: "DXUDJSU-XYB39500"
  user: "EMILYG888USW"
  role: "ACCOUNTADMIN"
  warehouse: "COMPUTE_WH"
  database: "CLAIMS_POC"
  schema_raw: "RAW"
  schema_ctrl: "CTRL"
  schema_int: "INT"
  schema_gold: "GOLD"
